### ISSUE TITLE
Support for file uploads

### ISSUE THREAD

**Issue by Martin-Idel** [cugu/swagger-go-chi#23]
Swagger 2.0 (as well as OpenAPI) supports file upload via https://swagger.io/docs/specification/2-0/file-upload/

Currently, this seems not supported by the generator. I guess the server template needs to be extended.

My suggestion:
- Parse 'formData' parameters as multipart form and generate code which provides the file data as `[]byte` array
- Parse the `Content-Type` header and pass it along with the file if it exists

In principle, it would be allowed to have several parts inside the multi-partite request (see Swagger spec), but maybe this wouldn't be as important to me personally.

**Comment by cugu** [comment]
Hi Martin, sound like a good approach. I will happily trust and merge any of your contributions 😉 Otherwise feel free to copy/fork this repo, but unfortunately I do not have time to implement this.

**Comment by Martin-Idel** [comment]
Sounds good, I'll have a look into it.
